import React, { Component } from 'react';
import { FlatList, View } from 'react-native';
import NotificationCell from './notif-cell'

export default class Notifications extends Component {
    static navigationOptions = { title: 'Notifications' }
    constructor(props) {
        super(props)
        this.state = {
            schedules: [
                {
                    _id: '1', //generated by Express
                    id: 1,
                    clubID: 1,
                    accountID: 3689251,
                    time: '2018-10-01 15:00:00',
                    type: 'Event',
                    eventStartTime: '2018-10-10 15:00',
                    eventEndTime: '2018-10-10 17:00',
                    desc: 'ipsum dolor sit amet consectetur',
                    proposalStatus: 'proposalStatus',
                    submitDate: 'submitDate',
                    reportStatus: 'reportStatus',
                    reportDate: 'reportDate',
                },
                {
                    _id: '2', //generated by Express
                    id: 2,
                    clubID: 1,
                    accountID: 3689251,
                    time: '2018-10-02 15:00:00',
                    type: 'Consultation',
                    eventStartTime: '2018-10-09 15:00',
                    eventEndTime: null,
                    desc: 'ipsum dolor sit amet consectetur',
                    proposalStatus: 'proposalStatus',
                    submitDate: 'submitDate',
                    reportStatus: 'reportStatus',
                    reportDate: 'reportDate',
                },
            ]
        }
    }
    render() {
        return (
            <View>
                <FlatList
                    data={this.state.schedules}
                    renderItem={({ item }) => <NotificationCell {...item} />}
                />
            </View>
        );
    }
}