import React, { Component } from 'react';
import { SectionList, View, Text, StyleSheet } from 'react-native';

export default class Notifications extends Component {
    static navigationOptions = { title: 'Notifications' }

    render() {
        var SAMPLE_DATA = [
            {
                _id: '1', //generated by Express
                id: 1,
                clubID: 1,
                accountID: 1,
                time: 1538038094, //(GMT): Thursday, September 27, 2018 8:48:14 AM
                type: 'EVENT',
                eventStartTime: 'eventStartTime', 
                eventEndTime: 'eventStartTime',
                desc: 'desc',
                proposalStatus: 'proposalStatus',
                submitDate: 'submitDate',
                reportStatus: 'reportStatus',
                reportDate: 'reportDate',
            }
        ]

        return (
            <View style={styles.container}>
                <SectionList
                    sections={[
                    ]}
                    renderItem={({ item }) => <Text style={styles.item}>{item}</Text>}
                    renderSectionHeader={({ section }) => <Text style={styles.sectionHeader}>{section.title}</Text>}
                    keyExtractor={(item, index) => index}
                />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingTop: 22,

    },
    sectionHeader: {
        paddingTop: 2,
        paddingLeft: 20,
        paddingRight: 10,
        paddingBottom: 2,
        fontSize: 12,
        color: 'gray',
        marginBottom: 4,
    },
    item: {
        paddingTop: 12,
        paddingLeft: 20,
        paddingRight: 10,
        paddingBottom: 12,
        fontSize: 14,
        backgroundColor: 'rgba(247,247,247,1.0)',
        marginBottom: 16,
    },
})